### ISSUE TITLE
Handle fetching -- freeze / no handle found

### ISSUE THREAD

**Issue by HotNoob** [fabianPas/MasterMarketeer#1]
EnumWindows(EnumerateWindowsCallback, 0);
got stuck in a loop; was just not getting any handles. on win 10. probs some stupid win 10 thing.  

replaced with another method of getting handle, and works fine now. 

`public void Collect()
        {
            //EnumWindows(EnumerateWindowsCallback, 0);

            Process[] processes = Process.GetProcesses();
            foreach (Process proc in processes)
            {

                if (proc.MainWindowTitle.Contains("Puzzle Pirates") && proc.MainWindowTitle.Contains("ocean"))
                {
                    _windowHandle = proc.MainWindowHandle;
                    Debug.WriteLine("Proc Found: " + proc.MainWindowTitle);
                    break;
                }
            }`

**Comment by fabianPas** [comment]
Could you set up a PR? Good find!

**Comment by HotNoob** [comment]
#4 + a bunch of other stuff.
